# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c9526404d7a5125ca4b823a7007cb2eb9c3e287bae869536296316e5411c94a1c12ffe1f03c936fa9c4a9c0b5f4dac8f41adefc80752a6121ccb142e79a001a

test:
  secret_key_base: 6e9010acf0d185413c3467125d6121d7746823557ac26b94fd717897575d174813178f7cd9aac4f6d5f535f564c03aaa3a1c2a1bdfdea6b723b9c3075791762b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
